export default {
    FETCHING       : 'FETCHING',
    SAVED          : 'SAVED',
    DAYBOXCLICK    : 'DAYBOXCLICK',
    ENTEREDITMODE  : 'ENTEREDITMODE',
    LEAVEEDITMODE  : 'LEAVEEDITMODE',
    CATEGORYCLICK  : 'CATEGORYCLICK',
    TOOLBOXCLICK   : 'TOOLBOXCLICK',
    TOGGLEINFO     : 'TOGGLEINFO',
    HIDEINFO       : 'HIDEINFO',
    FILTEREVENTS   : 'FILTEREVENTS',
    TOGGLEIMAGEBOX : 'TOGGLEIMAGEBOX',
    ERRORMESSAGE   : 'ERRORMESSAGE',
    HIDEMESSAGE    : 'HIDEMESSAGE'
}
